[Cyclactions]
; Do not tweak by hand! Use the Cycle Action editor instead ===
Version=3

[Main_Cyclactions]
Action1=item_preview_selection_stereo|IF|_RSd34d29336660cff0d857731f0d34ff340cbdeccf|42349|40129|41348|40209|_XENAKIOS_SELECTFIRSTTAKEOFITEMS|ELSE|40209|_XENAKIOS_SELECTFIRSTTAKEOFITEMS|ENDIF|
Nb_Actions=1
Version=3

